export type Dificuldade = 'Fácil' | 'Médio' | 'Difícil'
export type Potencial = 'Alto' | 'Médio'
export type Mercado = 'br' | 'global' | 'ambos'

export interface Ideia {
  id: number
  titulo: string
  problema: string
  publico: string
  monetizacao: string
  stack: string
  mvp: string
  dificuldade: Dificuldade
  potencial: Potencial
  mercado: Mercado
}

export interface Automacao {
  id: number
  titulo: string
  oQueFaz: string
  ferramentas: string
  fluxo: string[]
  monetizacao: string
}

export const ideias: Ideia[] = [
  {
    id: 1,
    titulo: 'Gerador de Contratos para Freelancers',
    problema: 'Freelancers brasileiros perdem horas criando contratos do zero e muitas vezes usam modelos inadequados sem cláusulas de proteção.',
    publico: 'Freelancers de design, dev, marketing e redação no Brasil',
    monetizacao: 'Freemium: 3 contratos/mês grátis, R$29/mês para ilimitado',
    stack: 'Next.js, Supabase, PDFKit, Stripe',
    mvp: 'Formulário com campos do projeto → gera PDF com contrato LGPD-compliant em português',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 2,
    titulo: 'Monitor de CNPJ com Alertas',
    problema: 'Empresas precisam monitorar situação de fornecedores, concorrentes ou CNPJ próprio na Receita Federal sem fazer consultas manuais.',
    publico: 'Contadores, jurídico de empresas, departamentos de compras',
    monetizacao: 'R$19/mês para até 10 CNPJs, R$49/mês para 50, R$149/mês para ilimitado',
    stack: 'Node.js, Supabase, API Receita WS, SendGrid',
    mvp: 'Cadastro de CNPJs → polling diário via API pública → email/WhatsApp se status muda',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 3,
    titulo: 'Link de Bio com Analytics',
    problema: 'Criadores de conteúdo querem uma página de links profissional com métricas reais de cliques, sem pagar caro por ferramentas genéricas.',
    publico: 'Criadores de conteúdo, influencers, profissionais que usam Instagram/TikTok',
    monetizacao: 'Grátis com subdomínio, R$19/mês para domínio próprio + analytics avançado',
    stack: 'Next.js, Supabase, Vercel, Cloudflare',
    mvp: 'Página de links customizável + contador de cliques por link + gráfico de visitas',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 4,
    titulo: 'Calculadora de Precificação para Freelancers',
    problema: 'A maioria dos freelancers cobra por feeling, sem considerar custos, impostos MEI, horas produtivas reais e margem de lucro.',
    publico: 'Freelancers e profissionais autônomos brasileiros',
    monetizacao: 'Grátis com marca d\'água no PDF, R$17/mês para PDF limpo + histórico',
    stack: 'Next.js, Supabase, React, PDFKit',
    mvp: 'Formulário com custos fixos, horas disponíveis, impostos → gera valor mínimo por hora e por projeto',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 5,
    titulo: 'Monitor de Uptime com Alertas WhatsApp',
    problema: 'Donos de sites pequenos ficam sabendo que o site caiu pelo cliente reclamar. Ferramentas existentes são caras ou mandam email (ignorado).',
    publico: 'Agências, desenvolvedores freelance, donos de e-commerce',
    monetizacao: 'R$0 para 3 sites, R$29/mês para 20 sites com alertas WhatsApp e relatório semanal',
    stack: 'Node.js, Supabase, Twilio/Evolution API, Railway',
    mvp: 'Cadastro de URLs → ping a cada 5 min → WhatsApp imediato se cair + email de relatório semanal',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 6,
    titulo: 'Gerador de Política de Privacidade LGPD',
    problema: 'Todo site brasileiro precisa de política de privacidade LGPD-compliant, mas contratar advogado é caro e templates genéricos não servem.',
    publico: 'Empreendedores digitais, agências, desenvolvedores que constroem sites para clientes',
    monetizacao: 'Grátis para 1 documento, R$47 por documento adicional, R$99/ano para ilimitado',
    stack: 'Next.js, OpenAI API, PDFKit, Stripe',
    mvp: 'Formulário sobre o negócio → gera política personalizada em PT-BR com IA + PDF para baixar',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 7,
    titulo: 'Calculadora de Impostos MEI',
    problema: 'MEIs não sabem ao certo quanto devem pagar de DAS, Imposto de Renda e quando precisam migrar para ME, gerando multas e surpresas fiscais.',
    publico: 'Microempreendedores individuais brasileiros',
    monetizacao: 'Freemium: cálculo mensal grátis, R$19/mês para histórico anual + alertas de limite de faturamento',
    stack: 'Next.js, Supabase, API Gov.br',
    mvp: 'Input de faturamento mensal → cálculo DAS + projeção anual + alerta se aproximando do limite MEI',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 8,
    titulo: 'Gerador de Propostas Comerciais',
    problema: 'Agências e freelancers gastam horas montando propostas no Word/Canva. Clientes recebem propostas amadoras que não convertem.',
    publico: 'Agências de marketing, design, dev; consultores independentes',
    monetizacao: 'R$39/mês para proposta ilimitada com analytics de abertura',
    stack: 'Next.js, Supabase, PDFKit, Resend, Stripe',
    mvp: 'Template de proposta + campos customizáveis → PDF profissional + link de visualização com rastreamento de abertura',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 9,
    titulo: 'CRM Simples para Autônomos',
    problema: 'CRMs existentes são complexos e caros para quem tem 10-50 clientes. Autônomos usam planilha e perdem follow-ups.',
    publico: 'Consultores, coaches, dentistas, advogados autônomos',
    monetizacao: 'R$29/mês para até 200 contatos, R$59/mês para ilimitado',
    stack: 'Next.js, Supabase, Resend',
    mvp: 'Cadastro de clientes + pipeline kanban + lembretes de follow-up por email/WhatsApp',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 10,
    titulo: 'Monitor de Preços de Concorrentes',
    problema: 'Lojistas precisam ajustar preços competitivamente mas monitorar concorrentes manualmente é inviável.',
    publico: 'Lojistas de e-commerce, gestores de marketplace',
    monetizacao: 'R$79/mês para 50 produtos monitorados, R$199/mês para 500',
    stack: 'Node.js, Puppeteer, Supabase, Redis, Resend',
    mvp: 'Cadastro de URLs de produtos concorrentes → scraping diário → alerta se preço muda + painel comparativo',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 11,
    titulo: 'Agendador de Posts com IA',
    problema: 'Criadores de conteúdo perdem tempo postando manualmente e não têm consistência. Ferramentas como Buffer são caras para pequenos criadores.',
    publico: 'Criadores de conteúdo, social media managers, pequenas empresas',
    monetizacao: 'R$39/mês para 3 canais, R$89/mês para 10 canais + sugestão de conteúdo com IA',
    stack: 'Next.js, Supabase, APIs do Instagram/LinkedIn/Twitter, OpenAI',
    mvp: 'Criação de post com IA → agendamento por calendário → publicação automática em múltiplos canais',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 12,
    titulo: 'Sistema de Agendamento para Prestadores',
    problema: 'Salões, clínicas e profissionais de saúde ainda agenciam por WhatsApp, perdendo tempo com confirmações e sofrendo com no-shows.',
    publico: 'Cabeleireiros, nutricionistas, psicólogos, fisioterapeutas',
    monetizacao: 'R$49/mês com lembretes automáticos por WhatsApp, R$89/mês para múltiplos profissionais',
    stack: 'Next.js, Supabase, Evolution API, Stripe',
    mvp: 'Página de agendamento público → confirmação automática → lembrete 24h antes via WhatsApp',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 13,
    titulo: 'Gerador de Posts LinkedIn com IA',
    problema: 'Profissionais sabem que precisam ser ativos no LinkedIn mas travam na hora de escrever. Posts genéricos não geram engajamento.',
    publico: 'Executivos, consultores, empreendedores que querem autoridade no LinkedIn',
    monetizacao: 'R$49/mês para 30 posts/mês, R$99/mês para ilimitado + agendamento',
    stack: 'Next.js, OpenAI GPT-4, Supabase, LinkedIn API',
    mvp: 'Input de tema/contexto → gera 3 variações de post com gancho + corpo + CTA → agendamento direto',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 14,
    titulo: 'Validador de Email em Massa',
    problema: 'Marketers têm listas de emails com 30-50% inválidos, o que prejudica entregabilidade e desperdiça dinheiro em disparos.',
    publico: 'Email marketers, growth hackers, agências de marketing',
    monetizacao: 'Créditos: R$0,005 por email validado, pacotes a partir de R$29',
    stack: 'Node.js, Supabase, Resend, Railway',
    mvp: 'Upload de CSV com emails → validação em batch (sintaxe + DNS + SMTP) → download do resultado limpo',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 15,
    titulo: 'Transcritor de Reuniões em Português',
    problema: 'Reuniões terminam sem ata. Ferramentas de transcrição em inglês erram muito em português, especialmente com sotaques regionais.',
    publico: 'Times de empresas brasileiras, consultores, jornalistas',
    monetizacao: 'R$49/mês para 5h de transcrição, R$149/mês para 20h',
    stack: 'Next.js, Whisper API/Groq, Supabase, OpenAI para resumo',
    mvp: 'Upload de áudio/vídeo → transcrição em PT-BR → resumo com próximos passos + exportar para Notion/Docs',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 16,
    titulo: 'Checker de Domínios em Massa',
    problema: 'Empreendedores querem verificar disponibilidade de muitos domínios de uma vez antes de decidir o nome do negócio.',
    publico: 'Empreendedores, agências de branding, investidores de domínios',
    monetizacao: 'Grátis para 10/dia, R$19/mês para ilimitado + alertas de expiração',
    stack: 'Node.js, Supabase, RDAP API, Cloudflare Workers',
    mvp: 'Input de lista de nomes → verifica disponibilidade .com .com.br .io → exporta relatório CSV',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 17,
    titulo: 'Monitor de Menções de Marca',
    problema: 'Pequenas empresas não sabem o que estão falando sobre elas online. Ferramentas de social listening custam R$500+/mês.',
    publico: 'PMEs, profissionais de marketing, gestores de comunidade',
    monetizacao: 'R$49/mês para 3 termos, R$129/mês para 15 termos com sentiment analysis',
    stack: 'Node.js, APIs Twitter/Reddit/Google, OpenAI para sentiment, Supabase',
    mvp: 'Cadastro de palavras-chave → coleta menções diárias → relatório com sentiment + alertas de menções negativas',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 18,
    titulo: 'Gerador de Scripts de Vendas com IA',
    problema: 'Times de vendas usam scripts genéricos que não convertem. Criar scripts personalizados por produto/público exige especialista caro.',
    publico: 'Gerentes de vendas, SDRs, donos de pequenas empresas',
    monetizacao: 'R$79/mês com acesso ilimitado + A/B testing de scripts',
    stack: 'Next.js, OpenAI GPT-4, Supabase',
    mvp: 'Input: produto, ICP, objeções comuns → gera script cold call + email outreach + WhatsApp + respostas para objeções',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 19,
    titulo: 'Sistema de NPS Automatizado',
    problema: 'Empresas coletam NPS manualmente ou pagam caro por ferramentas complexas. Maioria não fecha o loop com detratores.',
    publico: 'SaaS, e-commerce, prestadores de serviço B2B',
    monetizacao: 'R$49/mês para até 500 respostas/mês, R$149/mês para 5.000',
    stack: 'Next.js, Supabase, Resend, Stripe',
    mvp: 'Integração simples por email → coleta NPS → segmenta promotores/neutros/detratores → sequência automática de follow-up',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 20,
    titulo: 'Gerador de Thumbnails para YouTube',
    problema: 'Criadores de conteúdo perdem horas no Canva criando thumbnails. Thumbnails ruins = menos cliques, menos views.',
    publico: 'YouTubers, criadores de cursos online, podcasters com vídeo',
    monetizacao: 'R$29/mês para 30 thumbnails, R$79/mês para ilimitado',
    stack: 'Next.js, Stability AI/DALL-E, Canvas API, Supabase',
    mvp: 'Input de título + upload de foto do rosto → gera 3 variações de thumbnail profissional + editor simples',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 21,
    titulo: 'Painel de Vendas para Afiliados',
    problema: 'Afiliados Hotmart, Monetizze e Kiwify precisam acessar múltiplas plataformas para ver métricas. Não há visão unificada.',
    publico: 'Afiliados e produtores de infoprodutos no Brasil',
    monetizacao: 'R$39/mês para conexão com 3 plataformas, R$79/mês para todas',
    stack: 'Next.js, Supabase, APIs Hotmart/Kiwify/Monetizze, Recharts',
    mvp: 'Integração via API com Hotmart → painel com vendas, comissões, conversão por produto + exportação CSV',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 22,
    titulo: 'Sistema de Feedback Anônimo',
    problema: 'Empresas querem feedback honesto de funcionários mas pesquisas internas inibem respostas reais por medo de identificação.',
    publico: 'RH de PMEs, gestores de time, líderes de startups',
    monetizacao: 'R$29/mês para até 50 funcionários, R$89/mês para 200',
    stack: 'Next.js, Supabase, Resend',
    mvp: 'Link de formulário anônimo → coleta respostas → painel de temas recorrentes com word cloud + tendências',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 23,
    titulo: 'Compressor de Imagens em Batch',
    problema: 'Desenvolvedores e designers precisam comprimir dezenas de imagens para web. Ferramentas online processam uma por vez.',
    publico: 'Desenvolvedores web, designers, gestores de e-commerce',
    monetizacao: 'Grátis para 20MB/dia, R$19/mês para 1GB/dia + API',
    stack: 'Next.js, Sharp.js, Cloudflare Workers, R2',
    mvp: 'Drag-and-drop de múltiplas imagens → compressão em batch com configuração de qualidade → download em ZIP',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 24,
    titulo: 'Monitor de SEO para Pequenos Sites',
    problema: 'Pequenas empresas não acompanham posicionamento no Google. Ferramentas como Semrush custam R$500+/mês.',
    publico: 'Pequenas empresas, blogueiros, agências de marketing digital',
    monetizacao: 'R$49/mês para 50 keywords, R$99/mês para 200 keywords',
    stack: 'Next.js, Google Search Console API, Supabase, Recharts',
    mvp: 'Integração com Google Search Console → dashboard de keywords com histórico + alertas de queda de posição',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 25,
    titulo: 'Sistema de Cobrança Recorrente Simples',
    problema: 'Prestadores de serviço cobram clientes mensais de forma manual (Pix, boleto avulso), gerando inadimplência e trabalho operacional.',
    publico: 'Freelancers com clientes recorrentes, academias, escola de idiomas',
    monetizacao: '1% sobre transações processadas + R$0,50 por cobrança bem-sucedida',
    stack: 'Next.js, Supabase, Pagar.me/Asaas, Stripe',
    mvp: 'Cadastro de cliente + valor + dia de vencimento → gera cobrança automática mensal + notifica por email/WhatsApp',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 26,
    titulo: 'Documentador de APIs com IA',
    problema: 'Desenvolvedores odeiam escrever documentação de API. Documentações desatualizadas causam retrabalho e frustração na integração.',
    publico: 'Times de desenvolvimento, empresas com APIs internas ou públicas',
    monetizacao: 'R$79/mês para projetos ilimitados, versão enterprise R$299/mês',
    stack: 'Next.js, OpenAI, Supabase, GitHub Actions',
    mvp: 'Upload de coleção Postman ou código fonte → gera documentação Swagger/OpenAPI em português + página pública',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'global',
  },
  {
    id: 27,
    titulo: 'Rastreador de Encomendas Unificado',
    problema: 'Compradores online precisam checar múltiplas transportadoras manualmente. Correios, Jadlog, Sequoia — cada uma tem seu site.',
    publico: 'Compradores online, pequenos lojistas, gestores de e-commerce',
    monetizacao: 'Grátis para consumidor, R$49/mês para lojistas com múltiplos pedidos + API',
    stack: 'Node.js, Supabase, APIs transportadoras, Puppeteer para scrapers',
    mvp: 'Input de código de rastreio → identifica transportadora → exibe status atualizado + notificação quando chega',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 28,
    titulo: 'Gerador de Conteúdo Evergreen com IA',
    problema: 'Criadores de conteúdo precisam de artigos/posts que gerem tráfego por meses. Conteúdo evergreen bem feito exige pesquisa e expertise.',
    publico: 'Blogueiros, gestores de conteúdo, agências de inbound',
    monetizacao: 'R$79/mês para 20 artigos, R$199/mês para 100 artigos com otimização SEO',
    stack: 'Next.js, OpenAI GPT-4, Google Search API, Supabase',
    mvp: 'Input de nicho + keyword → pesquisa as 10 melhores páginas ranqueadas → gera artigo estruturado e otimizado',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 29,
    titulo: 'Sistema de Onboarding para SaaS',
    problema: 'Churn nos primeiros 30 dias é o maior problema de SaaS. Onboardings ruins fazem usuários desistirem antes de ver o valor.',
    publico: 'Fundadores e times de produto de SaaS',
    monetizacao: 'R$149/mês até 1.000 MAU, R$399/mês até 10.000 MAU',
    stack: 'Next.js, Supabase, Resend, React, Stripe',
    mvp: 'Checklist interativo de onboarding embutível em qualquer app via script → rastreamento de progresso + emails automáticos',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'global',
  },
  {
    id: 30,
    titulo: 'Gerador de Changelog Automático',
    problema: 'Times de produto não comunicam atualizações. Usuários descobrem features novas por acidente ou não as usam por desconhecimento.',
    publico: 'Times de produto SaaS, desenvolvedores de apps',
    monetizacao: 'R$29/mês plano básico, R$79/mês com widget embutível + notificações por email',
    stack: 'Next.js, GitHub API, OpenAI para resumos, Supabase',
    mvp: 'Conecta ao repo GitHub → transforma commits/PRs em changelog em linguagem humana → página pública + widget embutível',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 31,
    titulo: 'Monitor de Estoque com Alertas',
    problema: 'Pequenos lojistas ficam sem estoque de produtos-chave sem perceber, perdendo vendas. Sistemas de ERP são caros e complexos.',
    publico: 'Lojistas físicos e online de pequeno porte',
    monetizacao: 'R$39/mês para até 200 SKUs, R$89/mês para 1.000 SKUs',
    stack: 'Next.js, Supabase, Evolution API (WhatsApp), Stripe',
    mvp: 'Cadastro de produtos com estoque mínimo → alerta por WhatsApp quando atinge o mínimo + relatório semanal',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 32,
    titulo: 'Sistema de Agendamento de Mentorias',
    problema: 'Mentores gerenciam agendamentos por WhatsApp, sofrem com no-shows e perdem tempo com troca de mensagens para achar horário.',
    publico: 'Mentores, coaches, professores particulares, consultores',
    monetizacao: 'R$29/mês plano básico, R$69/mês com pacotes de sessões + pagamento integrado',
    stack: 'Next.js, Supabase, Google Calendar API, Stripe, Resend',
    mvp: 'Página de agendamento → integração Google Calendar → confirmação automática + lembrete 1h antes + link Zoom',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 33,
    titulo: 'Plataforma de Sistema de Pontos de Fidelidade',
    problema: 'Pequenos negócios perdem clientes para redes que têm programas de fidelidade robustos. Criar sistema próprio é caro.',
    publico: 'Restaurantes, cafeterias, pet shops, barbearias',
    monetizacao: 'R$49/mês básico, R$99/mês com app white-label e relatórios',
    stack: 'Next.js, Supabase, QR Code, Stripe',
    mvp: 'Dashboard do lojista + QR Code para cliente escanear na compra + app PWA para cliente ver pontos e resgatar',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 34,
    titulo: 'Gerador de Relatórios Financeiros em PDF',
    problema: 'PMEs precisam de relatórios financeiros para apresentar a sócios, bancos ou investidores, mas não têm contador disponível sempre.',
    publico: 'Empreendedores, CFOs de startups, gestores financeiros de PME',
    monetizacao: 'R$49/mês para relatórios ilimitados + templates customizáveis',
    stack: 'Next.js, Supabase, PDFKit, Chart.js, Stripe',
    mvp: 'Input de dados financeiros (DRE, fluxo de caixa) → gera relatório visual em PDF com gráficos profissionais',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 35,
    titulo: 'Integrador CRM + WhatsApp Business',
    problema: 'Times de vendas brasileiros trabalham no WhatsApp mas não têm CRM integrado. Conversas se perdem quando vendedor sai da empresa.',
    publico: 'Times de vendas de PMEs brasileiras',
    monetizacao: 'R$99/mês para 3 usuários, R$199/mês para 10 usuários',
    stack: 'Next.js, Supabase, Evolution API, Redis, Stripe',
    mvp: 'Número WhatsApp Business → toda conversa salva no CRM → atribuição de lead a vendedor + pipeline kanban',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 36,
    titulo: 'Calculadora de ROI de Campanhas',
    problema: 'Gestores de marketing não conseguem mostrar ROI real para a diretoria. Cada canal (Meta, Google, influencer) tem métricas diferentes.',
    publico: 'Gestores de marketing, donos de agências, CMOs de PMEs',
    monetizacao: 'R$39/mês básico, R$99/mês com integração automática Meta/Google Ads',
    stack: 'Next.js, Supabase, Meta Marketing API, Google Ads API',
    mvp: 'Input manual de investimento + receita por campanha → calcula ROI, ROAS, CPA, LTV → relatório comparativo',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 37,
    titulo: 'Sistema de Tickets de Suporte',
    problema: 'PMEs recebem suporte por WhatsApp, email e Instagram ao mesmo tempo, sem histórico centralizado. Tickets se perdem.',
    publico: 'Pequenas empresas com equipe de suporte de 2-10 pessoas',
    monetizacao: 'R$49/mês para 3 agentes, R$99/mês para 10 agentes',
    stack: 'Next.js, Supabase, Resend, Evolution API (WhatsApp)',
    mvp: 'Caixa de entrada unificada (email + WhatsApp) → criação automática de tickets → atribuição a agente + SLA',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 38,
    titulo: 'Monitor de Backlinks',
    problema: 'Sites perdem backlinks valiosos sem perceber, prejudicando SEO. Ferramentas de monitoramento custam centenas de dólares.',
    publico: 'SEO specialists, gestores de conteúdo, agências de SEO',
    monetizacao: 'R$49/mês para 1 domínio + 500 backlinks, R$149/mês para 5 domínios',
    stack: 'Node.js, Supabase, Ahrefs API, Resend',
    mvp: 'Import lista de backlinks → verificação semanal se ainda estão ativos → alerta imediato se link cai + histórico',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 39,
    titulo: 'Gerador de Anúncios com IA',
    problema: 'Criar variações de copy para anúncios Meta/Google é lento e exige copywriter. Times pequenos não têm escala para testar muitas variações.',
    publico: 'Gestores de tráfego pago, donos de e-commerce, agências de performance',
    monetizacao: 'R$79/mês para 100 variações/mês, R$199/mês para ilimitado com integração Meta/Google',
    stack: 'Next.js, OpenAI GPT-4, Supabase, Meta Marketing API',
    mvp: 'Input: produto, público, objetivo → gera 10 variações de headline + descrição + CTA otimizadas para cada plataforma',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 40,
    titulo: 'Sistema de Gestão de Projetos para Freelancers',
    problema: 'Freelancers usam Trello + planilha + WhatsApp para gerenciar projetos. Não há uma ferramenta focada no workflow freelancer.',
    publico: 'Freelancers de design, dev, marketing com múltiplos clientes simultâneos',
    monetizacao: 'R$39/mês com projetos ilimitados + relatório de horas + faturamento integrado',
    stack: 'Next.js, Supabase, Stripe',
    mvp: 'Kanban de projetos por cliente → timer de horas → geração de fatura baseada nas horas registradas',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 41,
    titulo: 'Validador de CNPJ/CPF em Lote',
    problema: 'Empresas precisam validar listas de CNPJs/CPFs de fornecedores, clientes ou parceiros antes de firmar contratos.',
    publico: 'Departamentos de compras, compliance, jurídico de empresas',
    monetizacao: 'R$0,01 por consulta, pacotes a partir de R$49',
    stack: 'Node.js, Supabase, API Receita Federal',
    mvp: 'Upload de planilha com CNPJs → consulta situação na Receita Federal → retorna planilha com status + dados da empresa',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 42,
    titulo: 'Plataforma de Micro-Mentoria',
    problema: 'Profissionais querem orientação pontual de especialistas mas sessões de 1h são caras e muitas vezes a dúvida é simples.',
    publico: 'Profissionais em transição de carreira, estudantes avançados, empreendedores iniciantes',
    monetizacao: 'Comissão de 20% por sessão de 30 minutos vendida na plataforma',
    stack: 'Next.js, Supabase, Stripe Connect, Whereby/Daily.co API',
    mvp: 'Marketplace de mentores com especialidades → agendamento de sessão de 15/30 min → videochamada integrada + pagamento',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 43,
    titulo: 'Sistema de Vouchers e Cupons',
    problema: 'Pequenos negócios não têm como criar campanhas de cupons profissionais. Oferecem desconto por WhatsApp sem rastreamento.',
    publico: 'Pequenas empresas, lojistas, prestadores de serviço',
    monetizacao: 'R$29/mês para cupons ilimitados, R$69/mês com integração em e-commerce',
    stack: 'Next.js, Supabase, QR Code API, Stripe',
    mvp: 'Criação de cupons com regras (% ou valor fixo, uso único, prazo) → QR code + link de validação no PDV',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 44,
    titulo: 'Agregador de Vagas Tech no Brasil',
    problema: 'Devs brasileiros precisam visitar 5+ sites (LinkedIn, Gupy, Trampos, Revelo) para achar vagas. Muitas vagas boas são de sites obscuros.',
    publico: 'Desenvolvedores e profissionais de TI brasileiros em busca de emprego',
    monetizacao: 'Grátis para candidatos, R$299/mês para empresas postarem vagas em destaque',
    stack: 'Next.js, Supabase, Puppeteer/Playwright, Meilisearch',
    mvp: 'Scraping de 10 principais fontes de vagas tech → agregação com busca por tecnologia/cidade/regime → alertas por email',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 45,
    titulo: 'Sistema de Assinatura de Documentos',
    problema: 'Empresas brasileiras ainda mandam contratos por email para assinar e escanear. DocuSign é caro e não aceita validade jurídica local facilmente.',
    publico: 'Advogados, RH, imobiliárias, gestores de contratos',
    monetizacao: 'R$0,80 por envelope assinado, R$99/mês para 150 envelopes',
    stack: 'Next.js, Supabase, PDFKit, Stripe, AWS S3',
    mvp: 'Upload de PDF → adicionar campos de assinatura → envio por email → assinatura via canvas → armazenamento seguro',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 46,
    titulo: 'Gerador de Bio Profissional com IA',
    problema: 'Profissionais travam na hora de escrever a própria bio para LinkedIn, portfólio ou press kit. Bios amadoras prejudicam credibilidade.',
    publico: 'Profissionais liberais, executivos, empreendedores, palestrantes',
    monetizacao: 'R$19 por bio gerada (one-time), R$49/mês para bios ilimitadas em vários formatos',
    stack: 'Next.js, OpenAI GPT-4, Supabase',
    mvp: 'Formulário com experiência e objetivos → gera bio em 3 versões (curta, média, longa) + versão inglês',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 47,
    titulo: 'Sistema de Gestão de Caixa para Pequenos Negócios',
    problema: 'Donos de pequeno comércio controlam caixa em caderninho ou planilha. Sem histórico confiável, tomam decisões cegas.',
    publico: 'Lojistas, restaurantes, prestadores de serviço com faturamento até R$500k/ano',
    monetizacao: 'R$39/mês com relatórios ilimitados, R$79/mês com múltiplos caixas/funcionários',
    stack: 'Next.js, Supabase, PWA (funciona offline), Stripe',
    mvp: 'Registro de entradas e saídas com categorias → fechamento de caixa diário → relatório mensal simples (DRE)',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 48,
    titulo: 'Gerador de Textos de Produto para E-commerce',
    problema: 'Lojistas com centenas de produtos gastam horas escrevendo descrições. Muitos copiam do fornecedor, prejudicando SEO.',
    publico: 'Lojistas de e-commerce, gestores de marketplace, dropshippers',
    monetizacao: 'Créditos: R$0,50 por descrição, pacotes a partir de R$29',
    stack: 'Next.js, OpenAI GPT-4, Supabase',
    mvp: 'Input: nome do produto + categoria + características → gera título SEO + descrição curta + descrição longa + bullet points',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 49,
    titulo: 'Monitor de Reviews do Google Meu Negócio',
    problema: 'Empresas não respondem reviews negativos a tempo porque ninguém monitora. Cada estrela perdida no Google afeta conversão.',
    publico: 'Pequenas e médias empresas com presença no Google Meu Negócio',
    monetizacao: 'R$29/mês para 1 local, R$79/mês para 5 locais com resposta sugerida por IA',
    stack: 'Next.js, Google Business Profile API, OpenAI, Supabase',
    mvp: 'Conecta Google Meu Negócio → alerta imediato de novo review → sugere resposta com IA → histórico de sentimento',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 50,
    titulo: 'URL Shortener com Analytics',
    problema: 'Marketers precisam de URLs curtas rastreáveis com métricas detalhadas. Bit.ly cobra caro para UTM automático e analytics completo.',
    publico: 'Marketers, afiliados, gestores de redes sociais',
    monetizacao: 'Grátis para 100 links/mês, R$29/mês para ilimitado + domínio customizado',
    stack: 'Next.js, Supabase, Cloudflare Workers, Recharts',
    mvp: 'Criação de link curto com UTM automático → painel de cliques por device/país/hora + link de expiração',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 51,
    titulo: 'Gerador de Paletas de Cores com IA',
    problema: 'Designers e não-designers gastam tempo buscando paletas harmonosas. Ferramentas atuais geram paletas aleatórias sem contexto de marca.',
    publico: 'Designers, empreendedores criando identidade visual, desenvolvedores frontend',
    monetizacao: 'Grátis para uso básico, R$19/mês para exportar em formatos profissionais + histórico',
    stack: 'Next.js, OpenAI, Chroma.js',
    mvp: 'Input de descrição da marca ou upload de logo → gera 3 paletas harmonosas com nome das cores + código HEX/RGB/HSL',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 52,
    titulo: 'Sistema de Automação de DMs',
    problema: 'Criadores e vendedores no Instagram recebem centenas de DMs. Responder manualmente é inviável e leads se perdem.',
    publico: 'Criadores de conteúdo com mais de 5k seguidores, vendedores no Instagram',
    monetizacao: 'R$49/mês para 1 conta + 1.000 DMs/mês, R$129/mês para 5 contas',
    stack: 'Next.js, Instagram Graph API, OpenAI, Supabase',
    mvp: 'Regras de resposta automática por palavra-chave + resposta inteligente com IA + qualificação de lead',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 53,
    titulo: 'Calculadora de Precificação para Infoprodutores',
    problema: 'Criadores de cursos e ebooks não sabem como precificar corretamente considerando plataforma, impostos, afiliados e margem.',
    publico: 'Infoprodutores iniciantes e intermediários no Brasil',
    monetizacao: 'Grátis para 1 produto, R$29/mês para portfólio completo + simulador de lançamento',
    stack: 'Next.js, Supabase',
    mvp: 'Input: custo de produção, tamanho de audiência, taxa da plataforma, comissão afiliado → calcula preço ideal + projeção de receita',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 54,
    titulo: 'Integrador de Múltiplos Marketplaces',
    problema: 'Lojistas vendem em Mercado Livre, Shopee e Amazon ao mesmo tempo. Gerenciar preços, estoque e pedidos em 3 plataformas é caótico.',
    publico: 'Lojistas que vendem em múltiplos marketplaces',
    monetizacao: 'R$149/mês para 3 marketplaces + 1.000 SKUs, R$399/mês para ilimitado',
    stack: 'Node.js, Supabase, APIs Mercado Livre/Shopee/Amazon, Redis',
    mvp: 'Integração com Mercado Livre → sincronização de estoque entre anúncios → painel unificado de pedidos',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 55,
    titulo: 'Gerador de Currículos Profissionais',
    problema: 'Candidatos usam templates de Word com design amador. ATS (sistemas de seleção) rejeitam currículos com formatação errada.',
    publico: 'Profissionais em busca de emprego, recém-formados',
    monetizacao: 'Grátis para 1 currículo básico, R$19 para PDF premium ATS-friendly, R$39/mês para ilimitado',
    stack: 'Next.js, Supabase, PDFKit, OpenAI para sugestões',
    mvp: 'Formulário estruturado → pré-visualização em tempo real → export PDF ATS-friendly + versão em inglês via IA',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 56,
    titulo: 'Sistema de Automação de Follow-up',
    problema: 'Vendedores esquecem de fazer follow-up de propostas enviadas. 80% das vendas exigem 5+ touchpoints mas maioria desiste no 2º.',
    publico: 'Vendedores B2B, times comerciais de PMEs, consultores',
    monetizacao: 'R$49/mês para 3 usuários, R$149/mês para 15 usuários',
    stack: 'Next.js, Supabase, Resend, Twilio',
    mvp: 'Cadastro de proposta enviada → sequência automática de follow-up (email dia 3, 7, 14) com template + rastreamento de abertura',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 57,
    titulo: 'Monitor de Compliance Fiscal',
    problema: 'PMEs brasileiras perdem prazos de obrigações fiscais (SPED, DCTF, EFD) por falta de controle, gerando multas pesadas.',
    publico: 'Contadores, gerentes financeiros, donos de PME',
    monetizacao: 'R$79/mês para 1 empresa, R$199/mês para escritório de contabilidade com clientes ilimitados',
    stack: 'Next.js, Supabase, Resend, Google Calendar API',
    mvp: 'Cadastro de obrigações fiscais da empresa → calendário com vencimentos + alertas 15/7/1 dia antes + checklist de entrega',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 58,
    titulo: 'Sistema de Split de Pagamentos',
    problema: 'Marketplaces e plataformas com múltiplos vendedores precisam dividir pagamentos automaticamente, o que é complexo de implementar.',
    publico: 'Fundadores de marketplaces e plataformas multi-vendedor',
    monetizacao: '0,5% sobre volume transacionado + R$0,30 por split realizado',
    stack: 'Next.js, Supabase, Stripe Connect, Redis',
    mvp: 'API simples de split: recebe pagamento → divide automaticamente entre N partes → repassa com schedule configurável',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 59,
    titulo: 'Painel de RH para PMEs',
    problema: 'PMEs não têm ferramentas de RH acessíveis. Planilhas de férias, ponto e avaliação são propensas a erro e difíceis de auditar.',
    publico: 'Gestores de RH e dono de PME com 10-100 funcionários',
    monetizacao: 'R$9/funcionário/mês com mínimo de R$69',
    stack: 'Next.js, Supabase, Resend, PWA',
    mvp: 'Controle de ponto por QR code + gestão de férias com saldo + avaliação de desempenho semestral',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 60,
    titulo: 'Sistema de Gestão de Contratos Recorrentes',
    problema: 'Empresas de serviço perdem contratos por vencimento silencioso. Renovações manuais geram gaps de cobrança e litígios.',
    publico: 'Empresas de software, agências de marketing, prestadoras de serviços B2B',
    monetizacao: 'R$49/mês para contratos ilimitados, R$129/mês com assinatura digital integrada',
    stack: 'Next.js, Supabase, Resend, PDFKit',
    mvp: 'Cadastro de contrato com prazo + renovação automática → alerta 60/30/15 dias antes do vencimento + histórico de versões',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 61,
    titulo: 'Gerador de Pitch Deck com IA',
    problema: 'Fundadores perdem semanas criando pitch decks. A estrutura importa tanto quanto o conteúdo, mas poucos sabem montar corretamente.',
    publico: 'Fundadores de startups, empreendedores buscando investimento',
    monetizacao: 'R$99 por pitch deck gerado (one-time), R$149/mês para iterações ilimitadas',
    stack: 'Next.js, OpenAI GPT-4, Google Slides API, Supabase',
    mvp: 'Formulário sobre o negócio (problema, solução, mercado, tração) → gera estrutura narrativa + slides no Google Slides',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 62,
    titulo: 'Monitor de Tráfego com Alertas',
    problema: 'Sites sofrem quedas de tráfego por mudanças de algoritmo ou problemas técnicos. GA4 não alerta automaticamente sobre anomalias.',
    publico: 'Gestores de SEO, analistas de marketing, donos de sites de conteúdo',
    monetizacao: 'R$39/mês para 3 sites, R$99/mês para 10 sites com análise de causa raiz com IA',
    stack: 'Next.js, Google Analytics API, OpenAI, Supabase, Resend',
    mvp: 'Integração GA4 → detecção automática de anomalia (queda >20% em 24h) → alerta com possíveis causas',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 63,
    titulo: 'Gerador de Newsletter com Curadoria',
    problema: 'Criadores de newsletter perdem horas curadoriando conteúdo. Processo manual de seleção → escrita → envio leva 4-8 horas/semana.',
    publico: 'Criadores de newsletter, jornalistas, especialistas de nicho',
    monetizacao: 'R$59/mês para newsletter ilimitada + curadoria automática',
    stack: 'Next.js, OpenAI, Resend, RSS feeds, Supabase',
    mvp: 'Cadastro de fontes RSS por tema → seleção automática dos melhores artigos da semana → rascunho de newsletter gerado + envio',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 64,
    titulo: 'Sistema de Gerenciamento de Depoimentos',
    problema: 'Empresas coletam depoimentos por WhatsApp e ficam espalhados. Exibir provas sociais organizadas no site aumenta conversão.',
    publico: 'Empreendedores digitais, coaches, agências, prestadores de serviço',
    monetizacao: 'R$29/mês para widget ilimitado, R$69/mês com vídeo depoimentos + integração Hotmart/Kiwify',
    stack: 'Next.js, Supabase, Cloudflare R2, Stripe',
    mvp: 'Link para cliente enviar depoimento em texto/áudio/vídeo → moderação → widget embutível no site com grid de depoimentos',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 65,
    titulo: 'Plataforma de Testes A/B para Landing Pages',
    problema: 'Empreendedores sabem que deveriam testar variações de landing page mas ferramentas como Optimizely custam R$1.000+/mês.',
    publico: 'Growth hackers, times de marketing de SaaS, e-commerce',
    monetizacao: 'R$79/mês para 3 experimentos simultâneos, R$199/mês para ilimitado',
    stack: 'Next.js, Supabase, Cloudflare Workers (edge), Recharts',
    mvp: 'Script de tracking + split de tráfego 50/50 → painel com conversões por variação + significância estatística',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'global',
  },
  {
    id: 66,
    titulo: 'Gerador de Contratos para Agências',
    problema: 'Agências criam contratos novos para cada cliente do zero. Falta de padronização gera inconsistências e vulnerabilidades legais.',
    publico: 'Agências de marketing, design, desenvolvimento web',
    monetizacao: 'R$49/mês para templates ilimitados + assinatura integrada',
    stack: 'Next.js, Supabase, PDFKit, Stripe',
    mvp: 'Templates de contrato por tipo de serviço (gestão de tráfego, design, desenvolvimento) + variáveis dinâmicas + PDF',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 67,
    titulo: 'Monitor de SERP Personalizado',
    problema: 'Profissionais de SEO precisam monitorar rankings para keywords específicas diariamente. Ferramentas existentes são complexas ou caras.',
    publico: 'SEO specialists, gestores de marketing de conteúdo, donos de sites de nicho',
    monetizacao: 'R$49/mês para 100 keywords, R$129/mês para 500 keywords',
    stack: 'Node.js, Supabase, Google Search API / SerpAPI, Recharts',
    mvp: 'Lista de keywords + domínio alvo → ranking diário + histórico em gráfico + alerta se cair mais de 5 posições',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 68,
    titulo: 'Plataforma de Reservas para Restaurantes',
    problema: 'Restaurantes gerenciam reservas por telefone e WhatsApp sem visibilidade de ocupação. No-shows derrubam o faturamento.',
    publico: 'Restaurantes, bares gastronômicos, bistrôs',
    monetizacao: 'R$99/mês com lembretes automáticos + lista de espera digital',
    stack: 'Next.js, Supabase, Evolution API, Stripe',
    mvp: 'Página de reserva pública → confirmação automática → lembrete 2h antes → gestão de mesas em grid visual',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 69,
    titulo: 'Sistema de Prospecção B2B Automatizada',
    problema: 'Times de vendas B2B gastam horas pesquisando leads manualmente no LinkedIn e validando emails que muitas vezes não existem.',
    publico: 'SDRs, BDRs, times de inside sales',
    monetizacao: 'R$149/mês para 500 leads/mês, R$399/mês para 2.000 leads/mês',
    stack: 'Node.js, Supabase, LinkedIn API, Hunter.io API, OpenAI',
    mvp: 'Input de ICP (cargo, setor, tamanho empresa) → busca leads qualificados → valida email → gera mensagem personalizada',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 70,
    titulo: 'Integrador de Multi-canais de Atendimento',
    problema: 'PMEs atendem no WhatsApp, Instagram, Messenger e email ao mesmo tempo mas sem histórico unificado do cliente.',
    publico: 'PMEs com equipe de atendimento de 2-15 pessoas',
    monetizacao: 'R$149/mês para 5 agentes + 3 canais, R$299/mês para 15 agentes + todos os canais',
    stack: 'Next.js, Supabase, Evolution API, Instagram Graph API, Resend, Redis',
    mvp: 'Caixa de entrada unificada WhatsApp + Instagram → histórico do cliente → atribuição de atendente + etiquetas',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 71,
    titulo: 'Gerador de Identidade Visual com IA',
    problema: 'Empreendedores iniciantes não têm budget para designer mas precisam de identidade visual profissional para validar o negócio.',
    publico: 'Empreendedores iniciantes, startups em fase de validação',
    monetizacao: 'R$97 por kit de identidade visual (one-time), R$49/mês para ilimitado',
    stack: 'Next.js, DALL-E 3, Stability AI, Supabase, Stripe',
    mvp: 'Formulário sobre o negócio + estilo desejado → gera logo + paleta de cores + tipografia + aplicações (cartão de visita, post)',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 72,
    titulo: 'Relatório de Redes Sociais Automatizado',
    problema: 'Gestores de social media perdem horas montando relatórios mensais para clientes em PowerPoint. Cada plataforma tem seus dados.',
    publico: 'Agências de marketing digital, social media managers freelance',
    monetizacao: 'R$49/mês para 3 clientes, R$149/mês para 20 clientes',
    stack: 'Next.js, APIs Meta/Instagram/LinkedIn/TikTok, PDFKit, Supabase',
    mvp: 'Conecta contas das redes sociais → consolida métricas do mês → gera PDF com gráficos prontos para apresentar ao cliente',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 73,
    titulo: 'Sistema de Gestão de Encomendas Personalizadas',
    problema: 'Artesãs, confeiteiras e ateliês recebem pedidos por WhatsApp sem controle. Produção fica bagunçada, prazos se perdem.',
    publico: 'Artesãs, confeiteiras, costureiras, criadores de produtos sob encomenda',
    monetizacao: 'R$29/mês com pedidos ilimitados, R$59/mês com site de vitrine + link de pedido',
    stack: 'Next.js, Supabase, Evolution API, Stripe',
    mvp: 'Formulário de pedido personalizado → kanban de produção → WhatsApp automático de status → pagamento antecipado',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 74,
    titulo: 'Monitor de Preços de Commodities',
    problema: 'Empresas do agro e indústria precisam acompanhar preços de commodities (soja, café, dólar) para timing de compra/venda.',
    publico: 'Agricultores, trading companies, indústria alimentícia',
    monetizacao: 'R$99/mês para alertas de preço + histórico 12 meses, R$299/mês com projeções por IA',
    stack: 'Node.js, Supabase, APIs de dados financeiros (B3, CEPEA), Resend',
    mvp: 'Seleção de commodities a monitorar → alerta por email/WhatsApp quando atinge preço-alvo + gráfico de histórico',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 75,
    titulo: 'Sistema de Gestão de Afiliados',
    problema: 'Infoprodutores e e-commerces que têm programa de afiliados próprio não têm como rastrear vendas e pagar comissões de forma confiável.',
    publico: 'Produtores de infoprodutos fora das grandes plataformas, e-commerces',
    monetizacao: 'R$99/mês para até 50 afiliados, R$299/mês para ilimitado',
    stack: 'Next.js, Supabase, Stripe, Pagar.me',
    mvp: 'Links únicos de afiliado com rastreamento de clique e venda → painel do afiliado com comissões → pagamento automático via PIX',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 76,
    titulo: 'Chat ao Vivo para E-commerce',
    problema: 'Pequenos e-commerces perdem vendas porque clientes têm dúvidas na hora de comprar e não há atendimento imediato.',
    publico: 'Pequenos e médios e-commerces independentes',
    monetizacao: 'R$49/mês para 2 agentes, R$99/mês para 10 agentes + chatbot de pré-atendimento',
    stack: 'Next.js, Supabase, WebSockets/Ably, Stripe',
    mvp: 'Widget de chat instalável por script → painel do agente → notificação push quando cliente inicia chat + histórico',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 77,
    titulo: 'Integrador Nota Fiscal + ERP Simples',
    problema: 'PMEs emitem NF-e mas dados não entram automaticamente no controle financeiro. Digitação manual gera erros e retrabalho.',
    publico: 'Contador de PME, gestores financeiros, donos de empresa',
    monetizacao: 'R$99/mês para importação ilimitada + conciliação bancária',
    stack: 'Node.js, Supabase, API SEFAZ, Stripe',
    mvp: 'Import de XML de NF-e → extração automática de dados → lançamento no financeiro + relatório de DRE atualizado',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 78,
    titulo: 'Gerador de Briefings de Projeto',
    problema: 'Agências recebem briefings vagos que geram retrabalho. Clientes não sabem o que informar. Reuniões de alinhamento se multiplicam.',
    publico: 'Agências de design, marketing, desenvolvimento',
    monetizacao: 'R$39/mês para briefings ilimitados por tipo de projeto',
    stack: 'Next.js, Supabase, OpenAI para análise de briefing, PDFKit',
    mvp: 'Formulário inteligente por tipo de projeto (identidade visual, site, campanha) → gera briefing estruturado + análise de completude',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 79,
    titulo: 'Monitor de Ranking em Marketplaces',
    problema: 'Vendedores de marketplace não sabem por que produtos de concorrentes ranqueiam melhor. Sem dados, não conseguem otimizar.',
    publico: 'Vendedores de Mercado Livre, Shopee, Amazon Brasil',
    monetizacao: 'R$79/mês para 100 produtos monitorados, R$199/mês para 500',
    stack: 'Node.js, Puppeteer, Supabase, Redis',
    mvp: 'URL de categoria + keywords → rastreamento diário de posição dos seus produtos + dos top concorrentes + histórico',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 80,
    titulo: 'Sistema de Email de Abandono de Carrinho',
    problema: '70% dos carrinhos são abandonados. E-commerces sem ferramenta de recuperação perdem bilhões. Ferramentas existentes são complexas.',
    publico: 'Donos de e-commerce independente, lojas em Shopify/WooCommerce',
    monetizacao: '2% das vendas recuperadas ou R$99/mês fixo',
    stack: 'Next.js, Supabase, Resend, OpenAI para personalização',
    mvp: 'Script de tracking + email automático em 1h, 24h e 72h após abandono com produto + desconto progressivo',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 81,
    titulo: 'Sistema de Integração com iFood',
    problema: 'Restaurantes que estão no iFood precisam transferir pedidos manualmente para o sistema interno, gerando erros e atrasos.',
    publico: 'Restaurantes e dark kitchens que operam pelo iFood',
    monetizacao: 'R$99/mês por loja integrada',
    stack: 'Node.js, iFood API, Supabase, Impressora Térmica API',
    mvp: 'Integração iFood → pedidos chegam automaticamente no painel → impressão automática na cozinha + status atualizado no iFood',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 82,
    titulo: 'Gerador de FAQs com IA',
    problema: 'Suporte recebe sempre as mesmas dúvidas. FAQ desatualizada ou inexistente sobrecarrega o time e frustra clientes.',
    publico: 'Times de CS/suporte, donos de produto, SaaS',
    monetizacao: 'R$39/mês para FAQ ilimitada + widget embutível + busca semântica',
    stack: 'Next.js, OpenAI, Supabase (pgvector), Stripe',
    mvp: 'Input de tickets de suporte históricos → gera FAQ organizada por categorias → widget de busca semântica para o site',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 83,
    titulo: 'Plataforma de Assinatura de Conteúdo',
    problema: 'Criadores de conteúdo dependem de plataformas como Hotmart e Kiwify que cobram altas comissões. Criar assinatura própria é complexo.',
    publico: 'Criadores de conteúdo, especialistas, educadores',
    monetizacao: '3% sobre receita gerada na plataforma + R$49/mês de mensalidade',
    stack: 'Next.js, Supabase, Stripe, Cloudflare R2',
    mvp: 'Área de membros com posts + vídeos + comunidade → cobrança recorrente via Stripe → acesso controlado por plano',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 84,
    titulo: 'Monitor de Score de Crédito Empresarial',
    problema: 'Empresas não sabem como estão sendo avaliadas por bancos e fornecedores. Score baixo causa juros altos e condições ruins.',
    publico: 'Donos de PME, CFOs de startups, empreendedores',
    monetizacao: 'R$59/mês para monitoramento contínuo + alertas + dicas de melhoria',
    stack: 'Node.js, APIs Serasa/SPC, Supabase, OpenAI para insights',
    mvp: 'Cadastro de CNPJ → consulta score → histórico de variações + alertas de mudança + sugestões para melhorar',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 85,
    titulo: 'Sistema de Integração para Criadores',
    problema: 'Criadores monetizam em múltiplas plataformas (Hotmart, Kiwify, Patreon, YouTube) mas não têm visão financeira unificada.',
    publico: 'Criadores de conteúdo e infoprodutores com múltiplas fontes de renda',
    monetizacao: 'R$39/mês para conexão com 3 plataformas, R$89/mês para todas',
    stack: 'Next.js, Supabase, APIs Hotmart/Kiwify/YouTube/Patreon, Recharts',
    mvp: 'Dashboard com receita unificada de todas as plataformas → gráfico de crescimento + breakdown por fonte',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 86,
    titulo: 'Agendador de Relatórios Automáticos',
    problema: 'Gestores precisam de relatórios recorrentes (semanal, mensal) mas analistas gastam horas montando sempre o mesmo documento.',
    publico: 'Times de operações, BI analysts, gestores que recebem relatórios recorrentes',
    monetizacao: 'R$79/mês para relatórios ilimitados, R$199/mês com conexões de banco de dados',
    stack: 'Next.js, Supabase, Resend, PDFKit, Chart.js',
    mvp: 'Conecta fonte de dados (planilha/banco) → define template do relatório → gera e envia automaticamente na data configurada',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 87,
    titulo: 'Sistema de Onboarding de Funcionários',
    problema: 'PMEs contratam novo funcionário e não têm processo estruturado. Informações importantes ficam na cabeça de uma pessoa.',
    publico: 'RH de PMEs, fundadores que estão crescendo o time',
    monetizacao: 'R$9/funcionário onboardado com mínimo de R$49/mês',
    stack: 'Next.js, Supabase, Resend',
    mvp: 'Checklist de onboarding por cargo → sequência de tarefas automáticas → assinatura de documentos → rastreamento de conclusão',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 88,
    titulo: 'Gerador de Whitepapers Técnicos',
    problema: 'Empresas de tech precisam de whitepapers para gerar leads B2B mas produzir conteúdo técnico aprofundado custa R$3.000-10.000 por documento.',
    publico: 'Empresas de software, consultorias de tech, startups B2B',
    monetizacao: 'R$299 por whitepaper (one-time), R$499/mês para produção contínua',
    stack: 'Next.js, OpenAI GPT-4, PDFKit, Supabase',
    mvp: 'Input de tema + dados internos da empresa → gera whitepaper estruturado (problema/solução/dados/conclusão) em PDF profissional',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 89,
    titulo: 'Sistema de Nutrição de Leads por Email',
    problema: 'Empresas captam leads mas não nutrem. 50% dos leads qualificados ainda não estão prontos para comprar na primeira interação.',
    publico: 'Times de marketing B2B, profissionais de inbound, agências',
    monetizacao: 'R$79/mês para 5.000 contatos, R$199/mês para 25.000',
    stack: 'Next.js, Supabase, Resend, Stripe',
    mvp: 'Sequência de emails configurável por trigger → personalização dinâmica → rastreamento de abertura e clique + pontuação de lead',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 90,
    titulo: 'Sistema de Depoimentos Pós-compra',
    problema: 'Empresas não coletam depoimentos sistematicamente. Pedir manualmente no WhatsApp é constrangedor e a maioria esquece.',
    publico: 'Infoprodutores, prestadores de serviço, e-commerce',
    monetizacao: 'R$29/mês para pedidos automáticos ilimitados, R$69/mês com widget de exibição',
    stack: 'Next.js, Supabase, Resend, Cloudflare R2',
    mvp: 'Webhook de compra concluída → email automático 7 dias depois pedindo depoimento → formulário simples + moderação',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 91,
    titulo: 'Gerador de Scripts para Vídeos Curtos',
    problema: 'Criadores de Reels/Shorts travam no roteiro. Vídeos sem estrutura narrativa têm baixa retenção e não viralizam.',
    publico: 'Criadores de conteúdo para Instagram Reels, YouTube Shorts, TikTok',
    monetizacao: 'R$39/mês para 50 scripts/mês, R$89/mês para ilimitado',
    stack: 'Next.js, OpenAI GPT-4, Supabase',
    mvp: 'Input de nicho + tema + gancho desejado → gera script de 30-60s com gancho, desenvolvimento e CTA em formato de teleprompter',
    dificuldade: 'Fácil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 92,
    titulo: 'Sistema de Pagamento para Profissionais de Saúde',
    problema: 'Médicos, psicólogos e dentistas cobram manualmente por Pix/boleto sem recibo profissional e sem controle de inadimplência.',
    publico: 'Profissionais de saúde autônomos e em consultório compartilhado',
    monetizacao: '1% sobre transações + R$29/mês de plataforma',
    stack: 'Next.js, Supabase, Pagar.me, Stripe',
    mvp: 'Link de pagamento por consulta → recibo automático por email → relatório mensal de receitas + lembretes de cobrança',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 93,
    titulo: 'Sistema de Gestão de Campanhas de Influencer',
    problema: 'Marcas gerenciam campanhas de influencer por planilha e email. Não há controle de entregas, prazos e ROI centralizado.',
    publico: 'Gestores de marketing de marcas com programa de influencers',
    monetizacao: 'R$149/mês para 10 influencers, R$399/mês para 50 influencers',
    stack: 'Next.js, Supabase, APIs sociais, Stripe',
    mvp: 'Cadastro de campanha + influencers contratados → checklist de entregas → upload de material → relatório de resultado',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 94,
    titulo: 'Monitor de Disponibilidade de APIs',
    problema: 'Desenvolvedores dependem de APIs de terceiros (Stripe, Twilio, etc.) e não são avisados quando essas APIs ficam instáveis.',
    publico: 'Desenvolvedores, SREs, times de DevOps',
    monetizacao: 'Grátis para 5 APIs, R$19/mês para 20 APIs com histórico de incidentes',
    stack: 'Node.js, Supabase, Resend, Slack API, Railway',
    mvp: 'Cadastro de endpoints de APIs externas → health check a cada minuto → alerta Slack/email em caso de falha',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'global',
  },
  {
    id: 95,
    titulo: 'Gerador de Plano de Negócios Simplificado',
    problema: 'Empreendedores precisam de plano de negócios para banco, investidor ou SEBRAE mas consultorias cobram R$5.000-20.000.',
    publico: 'Empreendedores buscando crédito ou investimento',
    monetizacao: 'R$97 por plano gerado (one-time), R$49/mês para revisões ilimitadas',
    stack: 'Next.js, OpenAI GPT-4, PDFKit, Supabase',
    mvp: 'Formulário de perguntas guiadas sobre o negócio → gera plano estruturado (mercado, financeiro, operacional) em PDF',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'br',
  },
  {
    id: 96,
    titulo: 'Sistema de Precificação Dinâmica para Hotéis',
    problema: 'Pousadas e hotéis pequenos cobram preço fixo o ano todo, perdendo receita em alta temporada e ficando vazios na baixa.',
    publico: 'Proprietários de pousadas, hotéis boutique, Airbnb hosts com múltiplos imóveis',
    monetizacao: '1% sobre receita de acomodação ou R$149/mês fixo',
    stack: 'Next.js, Supabase, Airbnb API, Booking API, ML simples',
    mvp: 'Conecta Airbnb/Booking → analisa ocupação e preços de concorrentes → sugere preço ótimo por período',
    dificuldade: 'Difícil',
    potencial: 'Alto',
    mercado: 'ambos',
  },
  {
    id: 97,
    titulo: 'Plataforma de Micro-cursos em Áudio',
    problema: 'Profissionais querem aprender mas não têm tempo para vídeos longos. Conteúdo em áudio de 5-10 min cabe em qualquer rotina.',
    publico: 'Profissionais ocupados que querem desenvolvimento pessoal e profissional',
    monetizacao: 'R$39/mês para acesso ilimitado, criadores recebem 70% da receita proporcional ao consumo',
    stack: 'Next.js, Supabase, Cloudflare R2, Stripe',
    mvp: 'Upload de áudio por criador → organização em trilhas → player com velocidade variável + progresso salvo',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 98,
    titulo: 'Sistema de Gestão de Embaixadores de Marca',
    problema: 'Marcas têm clientes apaixonados que poderiam ser embaixadores mas não há processo estruturado para recrutá-los e recompensá-los.',
    publico: 'Marcas de consumo, SaaS com comunidade ativa',
    monetizacao: 'R$99/mês para 50 embaixadores, R$299/mês para ilimitado',
    stack: 'Next.js, Supabase, Stripe',
    mvp: 'Programa de embaixadores com pontos por indicação + compartilhamento → loja de recompensas + ranking gamificado',
    dificuldade: 'Médio',
    potencial: 'Médio',
    mercado: 'ambos',
  },
  {
    id: 99,
    titulo: 'Gerador de Contratos de Parceria para Influencers',
    problema: 'Influencers fecham parcerias informalmente por DM sem contrato, gerando conflitos sobre entregas, prazos e pagamento.',
    publico: 'Influencers digitais e marcas que fazem parcerias',
    monetizacao: 'R$29/mês para influencers, R$99/mês para marcas com múltiplas parcerias',
    stack: 'Next.js, Supabase, PDFKit, Stripe',
    mvp: 'Template de contrato de parceria com campos: entregas, prazo, valor, exclusividade → assinatura digital → PDF armazenado',
    dificuldade: 'Fácil',
    potencial: 'Médio',
    mercado: 'br',
  },
  {
    id: 100,
    titulo: 'Sistema de Gestão de Assinaturas de Software',
    problema: 'Times de TI não sabem quantas ferramentas SaaS a empresa assina. Subscriptions esquecidas consomem budget sem que ninguém saiba.',
    publico: 'CTOs, gerentes de TI, heads de operações de PMEs',
    monetizacao: 'R$49/mês para até 50 subscriptions, R$129/mês para ilimitado',
    stack: 'Next.js, Supabase, Plaid API (extrato bancário), Resend',
    mvp: 'Conecta extrato bancário → identifica cobrança de SaaS → categoriza por time → alerta de renovação + gráfico de gasto',
    dificuldade: 'Médio',
    potencial: 'Alto',
    mercado: 'ambos',
  },
]

export const automacoes: Automacao[] = [
  {
    id: 1,
    titulo: 'Boas-vindas Automático para Novos Leads',
    oQueFaz: 'Quando um lead preenche qualquer formulário do seu site, ele recebe automaticamente uma sequência de boas-vindas por email com recursos relevantes e um convite para agendar uma call.',
    ferramentas: 'Make.com ou n8n + Resend + Supabase + Google Calendar',
    fluxo: [
      'Lead preenche formulário → webhook dispara no Make/n8n',
      'Dados do lead são salvos no Supabase',
      'Email de boas-vindas enviado via Resend em até 2 minutos',
      'Se não abriu em 48h → email de follow-up com assunto diferente',
      'Se abriu mas não agendou → email com link do Calendly após 72h',
    ],
    monetizacao: 'Cobrança como serviço de automação: R$500-1.500 de setup + R$200-500/mês de manutenção por cliente',
  },
  {
    id: 2,
    titulo: 'Sincronização Notion → Google Sheets',
    oQueFaz: 'Mantém uma planilha Google sempre atualizada com dados do Notion — útil para quem usa o Notion como CRM ou gestão de projetos mas precisa compartilhar com pessoas que só usam Sheets.',
    ferramentas: 'n8n self-hosted + Notion API + Google Sheets API',
    fluxo: [
      'Trigger: nova página criada ou atualizada no Notion',
      'n8n busca os dados da página via API',
      'Transforma propriedades do Notion no formato da planilha',
      'Verifica se a linha já existe na Sheets (busca por ID)',
      'Atualiza linha existente ou insere nova linha',
    ],
    monetizacao: 'Template vendável por R$97 no Gumroad ou como serviço por R$300-800/mês',
  },
  {
    id: 3,
    titulo: 'Backup Automático de Repositórios GitHub',
    oQueFaz: 'Faz backup diário de todos os repositórios de uma organização GitHub para um bucket S3/R2, mantendo histórico de 30 dias com compressão.',
    ferramentas: 'GitHub Actions + AWS S3 ou Cloudflare R2 + Shell script',
    fluxo: [
      'Cron job roda às 2h da manhã todo dia',
      'Script lista todos os repos da organização via API GitHub',
      'Para cada repo: clona com --mirror e comprime em .tar.gz',
      'Upload para bucket com nome: {repo}-{data}.tar.gz',
      'Remove backups com mais de 30 dias',
      'Envia relatório por email com status de cada backup',
    ],
    monetizacao: 'Script vendável por R$47 + setup como serviço por R$200-400/mês para empresas',
  },
  {
    id: 4,
    titulo: 'Relatório Semanal de Métricas por Email',
    oQueFaz: 'Todo domingo às 20h um email formatado com as métricas da semana chega automaticamente para o time — sem precisar acessar nenhum dashboard.',
    ferramentas: 'n8n ou Make + Google Analytics API + Supabase + Resend',
    fluxo: [
      'Cron job toda segunda-feira às 8h (referente à semana anterior)',
      'Busca métricas do Google Analytics (visitas, conversões, bounce)',
      'Busca dados do Supabase (novos usuários, receita, churn)',
      'Calcula variação percentual em relação à semana anterior',
      'Monta HTML do email com tabelas e setas de tendência',
      'Envia para lista de destinatários configurada',
    ],
    monetizacao: 'Serviço mensal de R$300-600 por cliente ou template por R$67',
  },
  {
    id: 5,
    titulo: 'Captura de Leads de Anúncios → CRM',
    oQueFaz: 'Leads gerados por Lead Ads do Facebook/Instagram ou Google Forms entram automaticamente no CRM com tag da campanha de origem e disparo imediato de mensagem no WhatsApp.',
    ferramentas: 'Make.com + Meta Lead Ads API + Evolution API (WhatsApp) + Pipedrive ou HubSpot',
    fluxo: [
      'Novo lead chega via Facebook Lead Ads webhook',
      'Make busca dados completos do lead na API da Meta',
      'Cria contato no CRM com todas as informações + tag da campanha',
      'Envia mensagem WhatsApp personalizada em até 5 minutos',
      'Cria tarefa no CRM para o vendedor responsivo fazer follow-up',
      'Adiciona à sequência de email de nutrição',
    ],
    monetizacao: 'Setup de R$800-2.000 + R$300-800/mês de manutenção por cliente',
  },
  {
    id: 6,
    titulo: 'Follow-up Automático de Propostas',
    oQueFaz: 'Quando uma proposta é marcada como enviada no CRM, uma sequência inteligente de follow-up começa automaticamente — parando assim que o cliente responder.',
    ferramentas: 'n8n + HubSpot/Pipedrive API + Resend + Twilio (SMS)',
    fluxo: [
      'Proposta marcada como "enviada" no CRM → webhook disparado',
      'Dia 3: email com pergunta aberta sobre dúvidas',
      'Dia 7: email com caso de uso similar ao do cliente',
      'Dia 14: email com deadline de validade da proposta',
      'Dia 21: SMS final com tom urgente',
      'Se cliente responder em qualquer ponto → cancela todos os próximos passos',
    ],
    monetizacao: 'Automação vendável como serviço por R$500 setup + R$200/mês',
  },
  {
    id: 7,
    titulo: 'Publicação Cross-Platform de Conteúdo',
    oQueFaz: 'Quando você publica um post no Notion ou escreve um artigo no blog, ele é automaticamente adaptado e publicado no LinkedIn, Twitter/X e na newsletter.',
    ferramentas: 'Make.com + Notion API + LinkedIn API + Twitter API + Resend',
    fluxo: [
      'Novo artigo publicado no Notion com status "Pronto para distribuir"',
      'Make busca o conteúdo completo via Notion API',
      'OpenAI adapta para formato LinkedIn (gancho + texto + hashtags)',
      'OpenAI cria thread de 5 tweets com os pontos principais',
      'Publica no LinkedIn e agenda no Twitter',
      'Envia resumo por email para a lista de newsletter com link para artigo completo',
    ],
    monetizacao: 'Serviço de automação de conteúdo por R$600-1.500/mês para empresas ou criadores',
  },
  {
    id: 8,
    titulo: 'Alerta de Menções da Marca em Redes Sociais',
    oQueFaz: 'Monitora Twitter/X, Reddit e comentários do YouTube em tempo real para mencionar o nome da empresa — alerta imediato se houver menções negativas.',
    ferramentas: 'n8n + Twitter API + Reddit API + OpenAI (sentiment) + Slack',
    fluxo: [
      'Polling a cada 30 minutos nas APIs do Twitter e Reddit',
      'Filtra resultados por palavra-chave (nome da marca + variações)',
      'OpenAI classifica sentiment: positivo, neutro ou negativo',
      'Menções negativas → alerta imediato no Slack com link + screenshot',
      'Menções positivas → relatório diário por email',
      'Salva histórico no banco de dados para análise de tendência',
    ],
    monetizacao: 'R$300-800/mês como serviço de monitoramento por cliente',
  },
  {
    id: 9,
    titulo: 'Geração Automática de Faturas Mensais',
    oQueFaz: 'No primeiro dia de cada mês, faturas são geradas e enviadas automaticamente para todos os clientes recorrentes com valor e vencimento configurados.',
    ferramentas: 'n8n + Supabase + PDFKit + Pagar.me ou Stripe + Resend',
    fluxo: [
      'Cron job no dia 1 de cada mês às 8h',
      'Busca todos os contratos ativos no Supabase',
      'Para cada cliente: gera PDF da fatura com dados fiscais',
      'Cria cobrança na plataforma de pagamento com link',
      'Envia email com PDF em anexo + link de pagamento',
      'Lembra em D+3 e D+7 se não pago + alerta interno se inadimplente',
    ],
    monetizacao: 'Setup de R$400-800 + R$150-300/mês de manutenção ou venda de template por R$79',
  },
  {
    id: 10,
    titulo: 'Onboarding Sequencial de Novos Clientes',
    oQueFaz: 'Quando um novo cliente é cadastrado, uma jornada de onboarding começa automaticamente: emails, tarefas internas, reunião agendada e materiais enviados na ordem certa.',
    ferramentas: 'n8n ou Make + Supabase + Resend + Calendly API + Slack',
    fluxo: [
      'Novo cliente criado no sistema → webhook dispara',
      'Dia 0: email de boas-vindas com credenciais e próximos passos',
      'Alerta no Slack para o CS responsável com dados do cliente',
      'Dia 1: email com link para agendar reunião de kickoff via Calendly',
      'Dia 3: envio automático de materiais de treinamento',
      'Dia 7: checklist de onboarding enviado por email para o cliente preencher',
      'Dia 14: pesquisa de satisfação automática',
    ],
    monetizacao: 'Automação de onboarding como serviço: R$800-2.000 setup + R$300-600/mês',
  },
  {
    id: 11,
    titulo: 'Resposta Automática de Suporte Nível 1',
    oQueFaz: 'Emails de suporte são triados por IA automaticamente — os simples recebem resposta imediata com a solução, os complexos são escalados para o agente humano.',
    ferramentas: 'n8n + Gmail API + OpenAI GPT-4 + Supabase (base de conhecimento) + Slack',
    fluxo: [
      'Email chega na caixa de suporte → webhook do Gmail dispara',
      'OpenAI classifica o ticket: urgência + categoria + complexidade',
      'Busca resposta relevante na base de conhecimento (embedding search)',
      'Se confiança > 85%: responde automaticamente com solução formatada',
      'Se confiança < 85%: cria ticket no Slack com resumo + categoria para agente humano',
      'Salva todas as interações para treinar a base de conhecimento',
    ],
    monetizacao: 'Serviço de automação de suporte: R$1.000-3.000 setup + R$500-1.500/mês',
  },
  {
    id: 12,
    titulo: 'Sincronização de Calendários Múltiplos',
    oQueFaz: 'Mantém Google Calendar pessoal, calendário da empresa e calendário de clientes sincronizados — bloqueios de disponibilidade aparecem em todos, sem conflito.',
    ferramentas: 'n8n + Google Calendar API (múltiplas contas) + Calendly API',
    fluxo: [
      'Evento criado em qualquer calendário conectado → trigger',
      'Verifica se o evento já existe nos outros calendários (evita duplicação)',
      'Cria evento bloqueador nos calendários que não têm o evento',
      'Atualiza o Calendly para bloquear o horário na agenda de agendamento',
      'Se evento cancelado em um calendário → cancela nos outros',
    ],
    monetizacao: 'Template de automação por R$47 ou setup como serviço por R$300-500',
  },
  {
    id: 13,
    titulo: 'Coleta e Análise de NPS Automático',
    oQueFaz: 'Após 30 dias de uso do produto, clientes recebem pesquisa NPS automática. Detratores recebem atenção imediata do CS; promotores são convidados a deixar review.',
    ferramentas: 'n8n + Supabase + Resend + Slack',
    fluxo: [
      'Cron job diário verifica clientes com 30 dias de conta',
      'Envia email com pesquisa NPS de 0 a 10 (link com token único)',
      'Cliente clica na nota → salva no banco + classifica automaticamente',
      'Nota 0-6 (Detrator): alerta urgente no Slack para CS + email personalizado de resolução',
      'Nota 7-8 (Neutro): email com novidades e recursos que podem não conhecer',
      'Nota 9-10 (Promotor): email pedindo review no G2/Google + convite para programa de embaixadores',
    ],
    monetizacao: 'Automação de NPS como serviço: R$500-1.000 setup + R$200-400/mês',
  },
  {
    id: 14,
    titulo: 'Pipeline de Aprovação de Conteúdo',
    oQueFaz: 'Conteúdo criado pela equipe passa por um fluxo automatizado de revisão — o criador é notificado de cada status e aprovações acontecem com um clique.',
    ferramentas: 'n8n + Notion API + Slack + Resend',
    fluxo: [
      'Conteúdo marcado como "Em revisão" no Notion → webhook',
      'Notificação no Slack para o revisor designado com link direto',
      'Revisor aprova ou solicita ajustes via botão no Slack',
      'Se aprovado: status muda para "Aprovado" + notifica o agendador',
      'Se ajuste: comentário vai para o Notion + notifica o criador',
      'Agendador publica no horário definido + atualiza status para "Publicado"',
    ],
    monetizacao: 'Setup de R$600-1.200 para agências ou equipes de conteúdo',
  },
  {
    id: 15,
    titulo: 'Email de Aniversário de Clientes',
    oQueFaz: 'Clientes recebem um email personalizado no aniversário com uma mensagem especial e um cupom de desconto, aumentando retenção e NPS.',
    ferramentas: 'n8n + Supabase + Resend',
    fluxo: [
      'Cron job roda todo dia às 9h',
      'Busca clientes com data de aniversário = hoje no banco',
      'Para cada cliente: gera cupom único com 15% de desconto válido por 7 dias',
      'Envia email personalizado com nome do cliente + cupom',
      'Registra o envio para não duplicar no mesmo ano',
      'Salva métrica de uso do cupom para análise de impacto',
    ],
    monetizacao: 'Automação simples: R$200-400 setup por cliente + R$100/mês de manutenção',
  },
  {
    id: 16,
    titulo: 'Reposição Automática de Estoque',
    oQueFaz: 'Quando o estoque de um produto cai abaixo do mínimo configurado, o sistema cria automaticamente um pedido de reposição para o fornecedor e alerta o gestor.',
    ferramentas: 'n8n + Supabase + Resend + Evolution API + integração com fornecedor (email/API)',
    fluxo: [
      'Atualização de estoque no sistema → trigger',
      'Verifica se produto atingiu o estoque mínimo configurado',
      'Calcula quantidade ideal para repor (baseado em histórico de vendas)',
      'Envia email automático para o fornecedor com pedido de compra em PDF',
      'Alerta WhatsApp para o gestor de compras para aprovação',
      'Registra pedido no sistema com status "Aguardando confirmação"',
    ],
    monetizacao: 'Automação de estoque: R$500-1.500 setup + R$200-500/mês para empresas',
  },
  {
    id: 17,
    titulo: 'Curadoria Automática para Newsletter',
    oQueFaz: 'Toda semana o sistema coleta artigos relevantes de fontes configuradas, seleciona os melhores por IA e cria um rascunho de newsletter pronto para revisar e enviar.',
    ferramentas: 'n8n + RSS feeds + OpenAI + Resend (ou Beehiiv API)',
    fluxo: [
      'Cron job toda quarta-feira às 10h',
      'Coleta artigos novos de todas as fontes RSS configuradas (últimos 7 dias)',
      'OpenAI pontua relevância de cada artigo para o nicho (0-10)',
      'Seleciona top 5 artigos com nota > 7',
      'Gera resumo de 3 linhas por artigo + introdução personalizada',
      'Cria rascunho na plataforma de email (Beehiiv/Resend) para revisão final',
      'Notifica o editor por email que o rascunho está pronto',
    ],
    monetizacao: 'Serviço de curadoria automática: R$400-800/mês por newsletter',
  },
  {
    id: 18,
    titulo: 'Dashboard de KPIs de Campanha em Tempo Real',
    oQueFaz: 'Consolida métricas de campanhas de múltiplas fontes (Meta, Google, email) em um único painel atualizado a cada hora, com alertas se algum KPI sair do esperado.',
    ferramentas: 'n8n + Meta Marketing API + Google Ads API + Resend + Supabase + Recharts',
    fluxo: [
      'Cron job a cada hora busca métricas de todas as plataformas',
      'Normaliza dados no mesmo formato no banco',
      'Calcula KPIs agregados: ROAS, CPC, CPL, CAC',
      'Verifica se KPI está fora do range configurado (ex: CPC > R$5)',
      'Se fora do range: alerta imediato por email + Slack',
      'Dashboard web atualizado automaticamente com gráficos de tendência',
    ],
    monetizacao: 'Serviço de analytics: R$800-2.000 setup + R$400-800/mês por cliente',
  },
  {
    id: 19,
    titulo: 'Notificação de Novos Pagamentos Recebidos',
    oQueFaz: 'Quando um pagamento é confirmado em qualquer plataforma (Stripe, Pagar.me, Kiwify), a equipe é notificada no Slack e o cliente recebe um email de confirmação personalizado.',
    ferramentas: 'n8n + Stripe Webhook + Slack API + Resend + Supabase',
    fluxo: [
      'Webhook de pagamento confirmado dispara no n8n',
      'Busca dados completos do pagamento e do cliente',
      'Envia mensagem no Slack com: nome do cliente, valor, produto comprado',
      'Envia email de confirmação personalizado para o cliente',
      'Atualiza registro do cliente no banco com novo status',
      'Se primeira compra: dispara sequência de onboarding',
    ],
    monetizacao: 'Automação de pagamentos: R$300-600 setup + integração como serviço',
  },
  {
    id: 20,
    titulo: 'Relatório de Ponto Automatizado',
    oQueFaz: 'Funcionários registram ponto por um formulário simples (ou WhatsApp) e ao final do mês o relatório completo de horas é gerado automaticamente em PDF.',
    ferramentas: 'n8n + Supabase + Evolution API (WhatsApp) + PDFKit + Resend',
    fluxo: [
      'Funcionário envia "entrada" ou "saída" por WhatsApp',
      'Sistema registra horário com nome do funcionário e tipo',
      'Calcula automaticamente horas trabalhadas por dia',
      'No último dia do mês: gera relatório em PDF por funcionário',
      'Envia PDF para o RH por email + disponibiliza link para o funcionário',
      'Destaca automaticamente atrasos, faltas e horas extras',
    ],
    monetizacao: 'Automação de ponto: R$500 setup + R$9/funcionário/mês',
  },
  {
    id: 21,
    titulo: 'Review de Código Automático com IA',
    oQueFaz: 'Quando um Pull Request é aberto no GitHub, um agente de IA revisa o código, aponta problemas de segurança, performance e padrões, e comenta diretamente no PR.',
    ferramentas: 'GitHub Actions + OpenAI GPT-4 + GitHub API',
    fluxo: [
      'PR aberto ou atualizado → GitHub Actions dispara',
      'Action faz checkout do diff e extrai arquivos modificados',
      'Envia cada arquivo para o GPT-4 com contexto do projeto',
      'GPT-4 revisa: segurança, performance, legibilidade, padrões',
      'Action posta comentários inline no PR com as sugestões',
      'Aprovação obrigatória da IA antes de merge (configurável)',
    ],
    monetizacao: 'GitHub Action publicada no marketplace por $9/mês ou template por R$47',
  },
  {
    id: 22,
    titulo: 'Alerta de Vencimento de Contratos',
    oQueFaz: 'Verifica diariamente os contratos cadastrados e envia alertas escalonados para a equipe comercial e para o cliente quando o vencimento se aproxima.',
    ferramentas: 'n8n + Supabase + Resend + Slack',
    fluxo: [
      'Cron job diário às 8h',
      'Busca contratos que vencem em 90, 60, 30, 15 e 7 dias',
      'Para 90 e 60 dias: alerta interno no Slack para o responsável comercial',
      'Para 30 dias: email para o cliente perguntando sobre renovação + alerta interno',
      'Para 15 dias: email urgente para cliente + task no CRM marcada como crítica',
      'Para 7 dias: alerta no Slack para o gerente + email final para cliente',
    ],
    monetizacao: 'Automação de contratos: R$400-800 setup + R$150-300/mês',
  },
  {
    id: 23,
    titulo: 'Nutrição de Leads com Conteúdo Personalizado',
    oQueFaz: 'Com base no comportamento do lead no site (páginas visitadas, materiais baixados), envia automaticamente conteúdo relevante ao interesse demonstrado.',
    ferramentas: 'n8n + Supabase + Resend + pixel de rastreamento customizado',
    fluxo: [
      'Lead baixa um material → tag "interesse-X" adicionado ao perfil',
      'Aguarda 24h para não parecer spam',
      'Envia email com artigo aprofundado sobre o mesmo tema',
      'Se abre o email: adiciona tag "engajado-X" + envia case de uso',
      'Se não abre em 3 dias: tenta assunto diferente sobre o mesmo tema',
      'Após 5 touchpoints sem resposta: pausa sequência por 30 dias',
    ],
    monetizacao: 'Automação de nutrição: R$800-2.000 setup + R$400-800/mês',
  },
  {
    id: 24,
    titulo: 'Coleta de Depoimentos Pós-compra',
    oQueFaz: 'Automatiza todo o ciclo de coleta de depoimentos: email no momento certo, formulário simples, aprovação e publicação no site — tudo sem intervenção manual.',
    ferramentas: 'n8n + Supabase + Resend + Cloudflare R2',
    fluxo: [
      'Compra confirmada → salva data e dados do cliente',
      'Dia 7 pós-compra: email pedindo opinião (pergunta aberta simples)',
      'Cliente responde → salva depoimento + solicita permissão de uso público',
      'Se autorizado: notifica gestor para aprovação via Slack',
      'Após aprovação: publica automaticamente no widget do site via API',
      'Envia email de agradecimento ao cliente com cupom de desconto',
    ],
    monetizacao: 'Automação de social proof: R$400-700 setup + R$150-300/mês',
  },
  {
    id: 25,
    titulo: 'Sincronização de Produtos entre Marketplaces',
    oQueFaz: 'Qualquer alteração de preço, estoque ou descrição feita em um marketplace é automaticamente refletida nos demais, evitando inconsistências e vendas de produtos sem estoque.',
    ferramentas: 'n8n + APIs Mercado Livre + Shopee + Amazon + Supabase',
    fluxo: [
      'Atualização em qualquer marketplace → webhook ou polling a cada 15min',
      'Identifica o que mudou: preço, estoque ou descrição',
      'Valida a mudança contra as regras de negócio configuradas',
      'Propaga a mudança para todos os outros marketplaces via API',
      'Registra log da sincronização com status de cada plataforma',
      'Alerta por WhatsApp se alguma plataforma retornar erro na atualização',
    ],
    monetizacao: 'Automação de marketplace: R$1.000-3.000 setup + R$400-1.000/mês por loja',
  },
]
